builder:
  track: dev

labels:
  app-group: estafette-ci
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 0

stages:
  build-lint-and-package:
    parallelStages:
      build:
        image: golang:1.16-alpine
        env:
          CGO_ENABLED: 0
          GOOS: linux
        commands:
        - go test ./...
        - go build -a -installsuffix cgo -ldflags "-X main.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

      lint-helm-chart:
        image: extensions/helm:dev
        action: lint

      package-helm-chart:
        image: extensions/helm:dev
        action: package

  bake:
    image: extensions/docker:dev
    action: build
    inline: |
      FROM scratch

      LABEL maintainer="estafette.io" \
            description="The ${ESTAFETTE_GIT_NAME} is the component that sends events to the api to trigger cron triggers"

      COPY ca-certificates.crt /etc/ssl/certs/
      COPY ${ESTAFETTE_GIT_NAME} /

      ENTRYPOINT ["/${ESTAFETTE_GIT_NAME}"]
    repositories:
    - estafette
    path: ./publish
    copy:
    - /etc/ssl/certs/ca-certificates.crt

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        repositories:
        - estafette

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        repositories:
        - estafette

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - estafette

  test-helm-chart:
    services:
    - name: kubernetes
      image: bsycorp/kind:latest-1.18
      env:
        REGISTRY: https://index.docker.io/v1/
        REGISTRY_USER: estafette.secret(aUPzjAEp9s4q9zXq.J23Bx8neYRtY1IYoLQOgd1eSm6DQkRyhhm9Mz_E_xg==.NHbU2dXELBFVzMAhOhKzLrKQqWe0vx0KJtzJTCAKkUy5Hl0TMeOeHGeOuIe4qOMXudjim3JOAEx_h9wUWC0Hj0vThQ==)
        REGISTRY_PASSWORD: estafette.secret(xogyCYWMKi3gul0z.tCai4Jf2vFHc8xcL8EGZuNg418x2xOB-thC4onZjcfMrh0WF4g9bIqvogqiopBOB.mXvlwrjF0UDj3ApW5EXMuY4hxdoD0fBknSWonFtnZdjXCfCIYHx6ZeCzsXmGEzzrgYJRp8t4bKN9pMT0MsOXvjsYkQ==)
      readiness:
        path: /kubernetes-ready
        port: 10080
        timeoutSeconds: 120
    image: extensions/helm:dev
    action: test
    values: |-
      logFormat: console

      config:
        queueSubject: cron-test

      image:
        pullPolicy: Always

      imagePullSecret:
        registryURL: https://index.docker.io/v1/
        username: estafette.secret(aUPzjAEp9s4q9zXq.J23Bx8neYRtY1IYoLQOgd1eSm6DQkRyhhm9Mz_E_xg==.NHbU2dXELBFVzMAhOhKzLrKQqWe0vx0KJtzJTCAKkUy5Hl0TMeOeHGeOuIe4qOMXudjim3JOAEx_h9wUWC0Hj0vThQ==)
        password: estafette.secret(xogyCYWMKi3gul0z.tCai4Jf2vFHc8xcL8EGZuNg418x2xOB-thC4onZjcfMrh0WF4g9bIqvogqiopBOB.mXvlwrjF0UDj3ApW5EXMuY4hxdoD0fBknSWonFtnZdjXCfCIYHx6ZeCzsXmGEzzrgYJRp8t4bKN9pMT0MsOXvjsYkQ==)

  clone-charts-repo:
    image: extensions/git-clone:dev
    repo: helm-charts
    branch: main

  publish-helm-chart:
    image: extensions/helm:dev
    action: publish
    repoBranch: main
  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'failed'

releases:
  tooling-estafette:
    clone: true
    stages:
      package-helm-chart:
        image: extensions/helm:dev
        action: package

      install:
        image: extensions/helm:dev
        action: install
        namespace: estafette-ci
        release: estafette-ci-cron-event-sender
        values: |-
          logFormat: v3

          cronjob:
            schedule: '* * * * *'

          extraEnv:
            - name: "JAEGER_AGENT_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: "JAEGER_SAMPLER_MANAGER_HOST_PORT"
              value: "http://$(JAEGER_AGENT_HOST):5778/sampling"
            - name: "JAEGER_SAMPLER_PARAM"
              value: "0.5"
            - name: "JAEGER_SAMPLER_TYPE"
              value: "probabilistic"
            - name: "JAEGER_SERVICE_NAME"
              value: "estafette-ci-cron-event-sender"

          imagePullSecret:
            registryURL: https://index.docker.io/v1/
            username: estafette.secret(aUPzjAEp9s4q9zXq.J23Bx8neYRtY1IYoLQOgd1eSm6DQkRyhhm9Mz_E_xg==.NHbU2dXELBFVzMAhOhKzLrKQqWe0vx0KJtzJTCAKkUy5Hl0TMeOeHGeOuIe4qOMXudjim3JOAEx_h9wUWC0Hj0vThQ==)
            password: estafette.secret(xogyCYWMKi3gul0z.tCai4Jf2vFHc8xcL8EGZuNg418x2xOB-thC4onZjcfMrh0WF4g9bIqvogqiopBOB.mXvlwrjF0UDj3ApW5EXMuY4hxdoD0fBknSWonFtnZdjXCfCIYHx6ZeCzsXmGEzzrgYJRp8t4bKN9pMT0MsOXvjsYkQ==)

          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 10
                preference:
                  matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: In
                    values:
                    - "true"

          tolerations:
          - key: cloud.google.com/gke-preemptible
            operator: Equal
            value: "true"
            effect: NoSchedule