builder:
  track: dev

labels:
  app-group: estafette-ci
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 0

stages:
  build:
    image: golang:1.14.4-alpine3.12
    env:
      CGO_ENABLED: 0
      GOOS: linux
      API_BASE_URL: estafette.secret(hs1Ldh4_O6z7C5Zv.SlX7bb1mn2kS0ew4O-1XUXWIklDPQ2YcE_bEZ3oXyJsz05Pad-dfZngljsrRmc5UhCp0GJUcYIHzwn6T.RUj7dbs-niUYz7c8LvxCQ3XSklqPSnwGFb7IfXoXl5Y7kt7caugEanZuidGCnWvJwlYKPLExiDPcOfapwnQ-Cv6wZg==)
      CLIENT_ID: estafette.secret(lC9Ed5g_v10tHBIX.2N27DLmUNK4mNtI2wselIAZJP3oaGLdbHZUAU9Ju23p35fSBtq2uNyHFDvxf8pQGtseCIw==.idGsUf2VL_RkOMgxhJ7wcVMKZiYHTKACSMsBRMdvznt_8PLDBiV1ILkas6wyLrBFeR-fTMsjxNilpkoB9xspWaO7Jg==)
      CLIENT_SECRET: estafette.secret(iQrFuXg9T08vyHLY.kUj4eAilZJt4HSuWD1XBjOoDsZlBfll164_YGnQ3R-smBdFl41QOnmL8uAF8zew4HZM_yfJ4zbesH9DeGGjGsmFjJBA4RffGn3EampEv_go=.m1jZc0yKEo1UPnbHGGDrt7dFpIFDLkVT9qyKAGAaROIeWIJH6hZBr0PxsyZnyLoPMIc3ugpe19QJyuzvg9fvXOIg6g==)
    commands:
    - go test ./...
    - go build -a -installsuffix cgo -ldflags "-X main.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

  bake:
    image: extensions/docker:dev
    action: build
    inline: |
      FROM scratch

      LABEL maintainer="estafette.io" \
            description="The ${ESTAFETTE_GIT_NAME} is the component that sends events to the api to trigger cron triggers"

      COPY ca-certificates.crt /etc/ssl/certs/
      COPY ${ESTAFETTE_GIT_NAME} /

      ENTRYPOINT ["/${ESTAFETTE_GIT_NAME}"]
    repositories:
    - estafette
    path: ./publish
    copy:
    - /etc/ssl/certs/ca-certificates.crt

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        repositories:
        - estafette

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        repositories:
        - estafette

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - estafette

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'failed'

releases:
  tooling-estafette:
    stages:
      deploy:
        image: extensions/gke:dev
        kind: cronjob
        schedule: '* * * * *'
        concurrencypolicy: Forbid
        namespace: estafette-ci
        container:
          repository: estafette
          env:
            API_BASE_URL: estafette.secret(hs1Ldh4_O6z7C5Zv.SlX7bb1mn2kS0ew4O-1XUXWIklDPQ2YcE_bEZ3oXyJsz05Pad-dfZngljsrRmc5UhCp0GJUcYIHzwn6T.RUj7dbs-niUYz7c8LvxCQ3XSklqPSnwGFb7IfXoXl5Y7kt7caugEanZuidGCnWvJwlYKPLExiDPcOfapwnQ-Cv6wZg==)
            CLIENT_ID: estafette.secret(lC9Ed5g_v10tHBIX.2N27DLmUNK4mNtI2wselIAZJP3oaGLdbHZUAU9Ju23p35fSBtq2uNyHFDvxf8pQGtseCIw==.idGsUf2VL_RkOMgxhJ7wcVMKZiYHTKACSMsBRMdvznt_8PLDBiV1ILkas6wyLrBFeR-fTMsjxNilpkoB9xspWaO7Jg==)
            CLIENT_SECRET: estafette.secret(iQrFuXg9T08vyHLY.kUj4eAilZJt4HSuWD1XBjOoDsZlBfll164_YGnQ3R-smBdFl41QOnmL8uAF8zew4HZM_yfJ4zbesH9DeGGjGsmFjJBA4RffGn3EampEv_go=.m1jZc0yKEo1UPnbHGGDrt7dFpIFDLkVT9qyKAGAaROIeWIJH6hZBr0PxsyZnyLoPMIc3ugpe19QJyuzvg9fvXOIg6g==)
            JAEGER_SAMPLER_TYPE: probabilistic
            JAEGER_SAMPLER_PARAM: 0.5
            ESTAFETTE_LOG_FORMAT: v3