apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-ci-cron-event-sender.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci-cron-event-sender.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.secret.valuesAreBase64Encoded }}
  clientSecret: {{.Values.secret.clientSecret | toString}}
  {{- else }}
  clientSecret: {{.Values.secret.clientSecret | toString | b64enc}}
  {{- end }}